/*
 * Copyright (c), ACCES I/O Products, Inc.
 * All rights reserved.
 *
 * Contributor(s):
 * Zach Perez, zach.perez@accesio.com
 *
 * PERMISSION TO USE, COPY, MODIFY, AND/OR DISTRIBUTE THIS SOFTWARE FOR ANY
 * PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT THE ABOVE
 * COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL COPIES.
 *
 * THIS SOFTWARE IS PROVIDED BY ACCES I/O AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ACCES I/O AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef ACCESIO_LINUX_IDS_H
#define ACCESIO_LINUX_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __KERNEL__
#include <stdint.h>
#include <stdbool.h>
#else
#include <linux/usb.h>
#endif



struct acces_usb_device_descriptor
{
    uint16_t pid_unloaded;
    uint16_t pid_loaded;
    const char *name;
    const char * fw_fname;
    int counters;
    unsigned int dio_bytes;
    unsigned int dio_config_bits;
    unsigned int tristate;
    int b_get_name;
    int b_set_custom_clocks;
    int b_dio_debounce;
    int b_dio_stream;
    int b_dio_spi;
    int b_clear_fifo;
    int b_dac_dio_stream;
    unsigned int imm_dacs;
    unsigned int imm_adcs;
    unsigned int wdg_bytes;
    int b_gate_selectable;
    double imm_adc_post_scale;
    int b_adc_bulk;
    unsigned int adc_channels;
    unsigned int adc_mux_channels;
    unsigned int config_bytes;
    unsigned short int range_shift;
    int b_dac_board_range;
    int flash_sectors;
    int b_dac_channel_cal;
    int b_dac_slow_wave_stream;
    int dacs_used;
    int b_adc_dio_stream;
    int b_dac_stream;
    double root_clock;
};

static const struct acces_usb_device_descriptor acces_usb_device_table[] =
{
{
    .pid_unloaded = 0x0001,
    .pid_loaded = 0x8001,
    .name = "usb_dio_32",
    .fw_fname = "USB_8001.hex",
    .counters = 3,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 1,
    .b_dio_debounce = 1,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 3000000.0,
},
{
    .pid_unloaded = 0x0004,
    .pid_loaded = 0x8004,
    .name = "usb_dio_32i",
    .fw_fname = "USB_8004.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 32,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 1,
},
{
    .pid_unloaded = 0x0005,
    .pid_loaded = 0x8005,
    .name = "usb_dio_24",
    .fw_fname = "USB_8006.hex",
    .counters = 0,
    .dio_bytes = 3,
    .dio_config_bits = 4,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 1,
},
{
    .pid_unloaded = 0x0002,
    .pid_loaded = 0x8002,
    .name = "usb_dio_48",
    .fw_fname = "USB_8003.hex",
    .counters = 0,
    .dio_bytes = 6,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0003,
    .pid_loaded = 0x8003,
    .name = "usb_dio_96",
    .fw_fname = "USB_8003.hex",
    .counters = 0,
    .dio_bytes = 12,
    .dio_config_bits = 0,
    .tristate = 0,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0006,
    .pid_loaded = 0x8006,
    .name = "usb_dio_24_ctr6",
    .fw_fname = "USB_8006.hex",
    .counters = 2,
    .dio_bytes = 3,
    .dio_config_bits = 4,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 1,
    .b_dio_debounce = 1,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x000C,
    .pid_loaded = 0x800C,
    .name = "usb_dio_16h",
    .fw_fname = "USB_800C.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 2,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 1,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 1,
    .imm_dacs = 1,
},
{
    .pid_unloaded = 0x000D,
    .pid_loaded = 0x800D,
    .name = "usb_di_16a",
    .fw_fname = "USB_800C.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 2,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 1,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 1,
    .imm_dacs = 1,
},
{
    .pid_unloaded = 0x000E,
    .pid_loaded = 0x800E,
    .name = "usb_do_16a",
    .fw_fname = "USB_800C.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 2,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 1,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 1,
    .imm_dacs = 1,
},
{
    .pid_unloaded = 0x000F,
    .pid_loaded = 0x800F,
    .name = "usb_dio_16a",
    .fw_fname = "USB_800C.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 2,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 1,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 1,
    .imm_dacs = 1,
},
{
    .pid_unloaded = 0x0010,
    .pid_loaded = 0x8010,
    .name = "usb_iiro_16",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0011,
    .pid_loaded = 0x8011,
    .name = "usb_ii_16",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0012,
    .pid_loaded = 0x8012,
    .name = "usb_ro_16",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0014,
    .pid_loaded = 0x8014,
    .name = "usb_iiro_8",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0015,
    .pid_loaded = 0x8015,
    .name = "usb_ii_8",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0016,
    .pid_loaded = 0x8016,
    .name = "usb_iiro_4",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0018,
    .pid_loaded = 0x8018,
    .name = "usb_idio_16",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0019,
    .pid_loaded = 0x8019,
    .name = "usb_ii_16_oem",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x001A,
    .pid_loaded = 0x801A,
    .name = "usb_ido_16",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x001C,
    .pid_loaded = 0x801C,
    .name = "usb_idio_8",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x001D,
    .pid_loaded = 0x801D,
    .name = "usb_ii_8_oem",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x001E,
    .pid_loaded = 0x801E,
    .name = "usb_idio_4",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x001F,
    .pid_loaded = 0x801F,
    .name = "usb_ii_4_oem",
    .fw_fname = "USB_8010.hex",
    .counters = 0,
    .dio_bytes = 4,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 1,
},
{
    .pid_unloaded = 0x0020,
    .pid_loaded = 0x8020,
    .name = "usb_ctr_15",
    .fw_fname = "USB_8020.hex",
    .counters = 5,
    .dio_bytes = 0,
    .dio_config_bits = 0,
    .tristate = 0,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 1,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0030,
    .pid_loaded = 0x8030,
    .name = "usb_iiro4_2sm",
    .fw_fname = "USB_8030.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0031,
    .pid_loaded = 0x8031,
    .name = "usb_iiro4_com",
    .fw_fname = "USB_8030.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0032,
    .pid_loaded = 0x8032,
    .name = "usb_dio_16_ro_8",
    .fw_fname = "usb_dio_16_ro_8",
    .counters = 0,
    .dio_bytes = 3,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x003C,
    .pid_loaded = 0x803C,
    .name = "usb_dio_48_do_24",
    .fw_fname = "USB_803C.hex",
    .counters = 0,
    .dio_bytes = 9,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x003D,
    .pid_loaded = 0x803D,
    .name = "usb_dio_24_do_12",
    .fw_fname = "USB_803C.hex",
    .counters = 0,
    .dio_bytes = 9,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x003E,
    .pid_loaded = 0x803E,
    .name = "usb_dio_24_do_12",
    .fw_fname = "USB_803C.hex",
    .counters = 0,
    .dio_bytes = 9,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0033,
    .pid_loaded = 0x8033,
    .name = "pico_dio_16_ro_8",
    .fw_fname = "USB_8033.hex",
    .counters = 0,
    .dio_bytes = 3,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
},
{
    .pid_unloaded = 0x0036,
    .pid_loaded = 0x8036,
    .name = "usbp_ii8_ido_4a",
    .fw_fname = "USB_8032.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 4.096/5.0,
},
{
    .pid_unloaded = 0x0037,
    .pid_loaded = 0x8037,
    .name = "pico_ii8_ido_4a",
    .fw_fname = "USB_8036.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = true,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 2,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 4.096/5.0,
},
{
    .pid_unloaded = 0x0040,
    .pid_loaded = 0x8040,
    .name = "usb_ai16_16a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0041,
    .pid_loaded = 0x8041,
    .name = "usb_ai16_16e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0042,
    .pid_loaded = 0x8042,
    .name = "usb_ai12_16a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0043,
    .pid_loaded = 0x8043,
    .name = "usb_ai12_16",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0044,
    .pid_loaded = 0x8044,
    .name = "usb_ai12_16e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0045,
    .pid_loaded = 0x8045,
    .name = "usb_ai16_64ma",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
},
{
    .pid_unloaded = 0x0046,
    .pid_loaded = 0x8046,
    .name = "usb_ai16_64me",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
},
{
    .pid_unloaded = 0x0047,
    .pid_loaded = 0x8047,
    .name = "usb_ai12_64ma",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
},
{
    .pid_unloaded = 0x0048,
    .pid_loaded = 0x8048,
    .name = "usb_ai12_64m",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
},
{
    .pid_unloaded = 0x0049,
    .pid_loaded = 0x8049,
    .name = "usb_ai12_64me",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
},
{
    .pid_unloaded = 0x004A,
    .pid_loaded = 0x804A,
    .name = "usb_ai16_32a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x004B,
    .pid_loaded = 0x804B,
    .name = "usb_ai16_32e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x004C,
    .pid_loaded = 0x804C,
    .name = "usb_ai12_32a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x004D,
    .pid_loaded = 0x804D,
    .name = "usb_ai12_32",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x004E,
    .pid_loaded = 0x804E,
    .name = "usb_ai12_32e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x004F,
    .pid_loaded = 0x804F,
    .name = "usb_ai16_64a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0050,
    .pid_loaded = 0x8050,
    .name = "usb_ai16_64e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0051,
    .pid_loaded = 0x8051,
    .name = "usb_ai12_64a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0052,
    .pid_loaded = 0x8052,
    .name = "usb_ai12_64",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0053,
    .pid_loaded = 0x8053,
    .name = "usb_ai12_64e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0054,
    .pid_loaded = 0x8054,
    .name = "usb_ai16_96a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0055,
    .pid_loaded = 0x8055,
    .name = "usb_ai16_96e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0056,
    .pid_loaded = 0x8056,
    .name = "usb_ai12_96a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0057,
    .pid_loaded = 0x8057,
    .name = "usb_ai12_96",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0058,
    .pid_loaded = 0x8058,
    .name = "usb_ai12_96e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0059,
    .pid_loaded = 0x8059,
    .name = "usb_ai16_128a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x005A,
    .pid_loaded = 0x805A,
    .name = "usb_ai16_128e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x005B,
    .pid_loaded = 0x805B,
    .name = "usb_ai12_128a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x005C,
    .pid_loaded = 0x805C,
    .name = "usb_ai12_128",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x005D,
    .pid_loaded = 0x805D,
    .name = "usb_ai12_128e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0068,
    .pid_loaded = 0x8068,
    .name = "usb_ao_arb1",
    .fw_fname = "USB_8068.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 1,
},
{
    .pid_unloaded = 0x0070,
    .pid_loaded = 0x8070,
    .name = "usb_ao16_16a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 16,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 16,
},
{
    .pid_unloaded = 0x0071,
    .pid_loaded = 0x8071,
    .name = "usb_ao16_16",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 16,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 16,
},
{
    .pid_unloaded = 0x0072,
    .pid_loaded = 0x8072,
    .name = "usb_ao16_12a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 12,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 12,
},
{
    .pid_unloaded = 0x0073,
    .pid_loaded = 0x8073,
    .name = "usb_ao16_12",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 12,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 12,
},
{
    .pid_unloaded = 0x0074,
    .pid_loaded = 0x8074,
    .name = "usb_ao16_8a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 8,
},
{
    .pid_unloaded = 0x0075,
    .pid_loaded = 0x8075,
    .name = "usb_ao16_8",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 8,
},
{
    .pid_unloaded = 0x0076,
    .pid_loaded = 0x8076,
    .name = "usb_ao16_4a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 4,
},
{
    .pid_unloaded = 0x0077,
    .pid_loaded = 0x8077,
    .name = "usb_ao16_4",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 4,
},
{
    .pid_unloaded = 0x0078,
    .pid_loaded = 0x8078,
    .name = "usb_ao12_16a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 16,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 16,
},
{
    .pid_unloaded = 0x0079,
    .pid_loaded = 0x8079,
    .name = "usb_ao12_16",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 16,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 16,
},
{
    .pid_unloaded = 0x007A,
    .pid_loaded = 0x807A,
    .name = "usb_ao12_12a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 12,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 12,
},
{
    .pid_unloaded = 0x007B,
    .pid_loaded = 0x807B,
    .name = "usb_ao12_12",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 12,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 12,
},
{
    .pid_unloaded = 0x007C,
    .pid_loaded = 0x807C,
    .name = "usb_ao12_8a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 8,
},
{
    .pid_unloaded = 0x007D,
    .pid_loaded = 0x807D,
    .name = "usb_ao12_8",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 8,
},
{
    .pid_unloaded = 0x007E,
    .pid_loaded = 0x807E,
    .name = "usb_ao12_4a",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 2,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 4,
},
{
    .pid_unloaded = 0x007F,
    .pid_loaded = 0x807F,
    .name = "usb_ao12_4",
    .fw_fname = "USB_8070.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 32,
    .b_dac_channel_cal = 1,
    .b_dac_slow_wave_stream = 1,
    .dacs_used = 4,
},
{
    .pid_unloaded = 0x0140,
    .pid_loaded = 0x8140,
    .name = "usb_aio16_16a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x015f,
    .pid_loaded = 0x815f,
    .name = "usb_aio16_16f",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0141,
    .pid_loaded = 0x8141,
    .name = "usb_aio16_16e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0142,
    .pid_loaded = 0x8142,
    .name = "usb_aio12_16a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0143,
    .pid_loaded = 0x8143,
    .name = "usb_aio12_16",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0144,
    .pid_loaded = 0x8144,
    .name = "usb_aio12_16e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 16,
    .config_bytes = 20,
    .range_shift = 0,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000.0,
},
{
    .pid_unloaded = 0x0145,
    .pid_loaded = 0x8145,
    .name = "usb_aio16_64ma",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
    .b_dac_board_range = 1,
},
{
    .pid_unloaded = 0x0146,
    .pid_loaded = 0x8146,
    .name = "usb_aio16_64me",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
    .b_dac_board_range = 1,
},
{
    .pid_unloaded = 0x0147,
    .pid_loaded = 0x8147,
    .name = "usb_aio12_64ma",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
    .b_dac_board_range = 1,
},
{
    .pid_unloaded = 0x0148,
    .pid_loaded = 0x8148,
    .name = "usb_aio12_64m",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
    .b_dac_board_range = 1,
},
{
    .pid_unloaded = 0x0149,
    .pid_loaded = 0x8149,
    .name = "usb_aio12_64me",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 2,
    .b_dac_board_range = 1,
},
{
    .pid_unloaded = 0x014A,
    .pid_loaded = 0x814A,
    .name = "usb_aio16_32a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x014B,
    .pid_loaded = 0x814B,
    .name = "usb_aio16_32e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x014C,
    .pid_loaded = 0x814C,
    .name = "usb_aio12_32a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x014D,
    .pid_loaded = 0x814D,
    .name = "usb_aio12_32",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x014F,
    .pid_loaded = 0x814F,
    .name = "usb_aio16_64a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 32,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0150,
    .pid_loaded = 0x8150,
    .name = "usb_aio16_64e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0151,
    .pid_loaded = 0x8151,
    .name = "usb_aio12_64a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0152,
    .pid_loaded = 0x8152,
    .name = "usb_aio12_64",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0153,
    .pid_loaded = 0x8153,
    .name = "usb_aio12_64e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 64,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0154,
    .pid_loaded = 0x8154,
    .name = "usb_aio16_96a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0155,
    .pid_loaded = 0x8155,
    .name = "usb_aio16_96e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0156,
    .pid_loaded = 0x8156,
    .name = "usb_aio12_96a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0157,
    .pid_loaded = 0x8157,
    .name = "usb_aio12_96",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0158,
    .pid_loaded = 0x8158,
    .name = "usb_aio12_96e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 96,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x015A,
    .pid_loaded = 0x815A,
    .name = "usb_aio16_128e",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x015B,
    .pid_loaded = 0x815B,
    .name = "usb_aio12_128a",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x015C,
    .pid_loaded = 0x815C,
    .name = "usb_aio12_128",
    .fw_fname = "USB_815F.hex",
    .counters = 1,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 1,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 4,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 1,
    .adc_channels = 16,
    .adc_mux_channels = 128,
    .config_bytes = 21,
    .range_shift = 3,
    .b_dac_board_range = 1,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 0,
    .root_clock = 10000000,
},
{
    .pid_unloaded = 0x0180,
    .pid_loaded = 0x8180,
    .name = "usb_ai16_2a",
    .fw_fname = "USB_8180.hex",
    .counters = 0,
    .dio_bytes = 2,
    .dio_config_bits = 0,
    .tristate = 0,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 1,
    .b_dio_spi = 0,
    .b_clear_fifo = 1,
    .b_dac_dio_stream = 0,
    .imm_dacs = 0,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 2,
    .adc_mux_channels = 2,
    .config_bytes = 2,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 0,
    .b_adc_dio_stream = 1,
    .b_dac_stream = 0,
    .root_clock = 1000000,
},
{
    .pid_unloaded = 0xC002,
    .pid_loaded = 0x4002,
    .name = "usb_da12_8a",
    .fw_fname = "USB_4002.hex",
    .counters = 0,
    .dio_bytes = 0,
    .dio_config_bits = 0,
    .tristate = 0,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
    .imm_adcs = 0,
    .wdg_bytes = 0,
    .b_gate_selectable = 0,
    .imm_adc_post_scale = 0,
    .b_adc_bulk = 0,
    .adc_channels = 0,
    .adc_mux_channels = 0,
    .config_bytes = 0,
    .range_shift = 0,
    .b_dac_board_range = 0,
    .flash_sectors = 0,
    .b_dac_channel_cal = 0,
    .b_dac_slow_wave_stream = 0,
    .dacs_used = 5,
    .b_adc_dio_stream = 0,
    .b_dac_stream = 1,
},
{
    .pid_unloaded = 0xC003,
    .pid_loaded = 0x4003,
    .name = "usb_da12_8e",
    .fw_fname = "USB_4003.hex",
    .counters = 0,
    .dio_bytes = 0,
    .dio_config_bits = 0,
    .tristate = 0,
    .b_get_name = 1,
    .b_set_custom_clocks = 0,
    .b_dio_debounce = 0,
    .b_dio_stream = 0,
    .b_dio_spi = 0,
    .b_clear_fifo = 0,
    .b_dac_dio_stream = 0,
    .imm_dacs = 8,
},
};

#define NUM_ACCES_USB_DEVICES sizeof(acces_usb_device_table)/sizeof(acces_usb_device_table[0])

#define ACCESIO_USB_VID 0x1605


// There must be two entries in acces_usb_id_table for every entry in
// acces_usb_device_table. One for pid_unloaded and one for pid_loaded. Keeping
// them in the same order is enforced. Module will not load if the tables don't
// match

#ifdef __KERNEL__

static struct usb_device_id acces_usb_id_table[] =
{
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0001},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8001},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0004},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8004},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0005},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8005},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0002},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8002},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0003},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8003},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0006},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8006},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x000C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x800C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x000D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x800D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x000E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x800E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x000F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x800F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0010},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8010},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0011},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8011},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0012},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8012},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0014},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8014},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0015},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8015},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0016},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8016},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0018},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8018},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0019},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8019},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x001A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x801A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x001C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x801C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x001D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x801D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x001E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x801E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x001F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x801F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0020},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8020},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0030},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8030},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0031},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8031},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0032},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8032},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x003C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x803C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x003D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x803D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x003E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x803E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0033},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8033},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0036},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8036},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0037},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8037},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0040},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8040},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0041},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8041},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0042},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8042},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0043},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8043},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0044},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8044},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0045},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8045},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0046},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8046},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0047},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8047},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0048},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8048},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0049},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8049},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x004F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x804F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0050},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8050},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0051},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8051},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0052},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8052},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0053},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8053},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0054},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8054},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0055},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8055},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0056},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8056},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0057},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8057},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0058},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8058},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0059},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8059},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x005A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x805A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x005B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x805B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x005C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x805C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x005D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x805D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0068},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8068},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0070},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8070},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0071},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8071},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0072},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8072},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0073},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8073},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0074},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8074},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0075},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8075},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0076},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8076},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0077},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8077},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0078},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8078},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0079},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8079},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807E},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x007F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x807F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0140},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8140},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x015f},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x815f},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0141},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8141},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0142},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8142},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0143},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8143},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0144},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8144},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0145},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8145},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0146},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8146},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0147},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8147},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0148},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8148},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0149},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8149},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x014A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x814A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x014B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x814B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x014C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x814C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x014D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x814D},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x014F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x814F},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0150},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8150},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0151},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8151},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0152},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8152},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0153},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8153},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0154},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8154},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0155},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8155},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0156},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8156},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0157},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8157},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0158},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8158},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x015A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x815A},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x015B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x815B},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x015C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x815C},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x0180},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x8180},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0xC002},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x4002},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0xC003},
    { .match_flags = USB_DEVICE_ID_MATCH_DEVICE, .idVendor = ACCESIO_USB_VID, .idProduct = 0x4003},
    {0}, //Must end in NULL entry. This is accounted for in NUM_ACCES_ID_ENTRIES macro
};

#define NUM_ACCES_ID_ENTRIES sizeof(acces_usb_id_table)/sizeof(acces_usb_id_table[0]) - 1


#endif //__KERNEL__





// VENDOR ID

#ifdef __cplusplus
}
#endif

#endif // ACCESIO_LINUX_IDS_H